/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts.edu.fpoo.vista;

import java.awt.Color;
import uts.edu.fpoo.controlador.MesasControlador;
import uts.edu.fpoo.controlador.PlatosControlador;

/**
 *
 * @author sebas
 */
public class MenuOpciones extends javax.swing.JFrame {

    
    public MenuOpciones() {
        initComponents();
        this.setSize(1200,700);
        Color fondoSuave = new Color(100, 100, 255); // Azul muy claro (AliceBlue)
contentPanel.setBackground(fondoSuave);
getContentPane().setBackground(fondoSuave);

        contentPanel.setLayout(new java.awt.BorderLayout());


javax.swing.JLabel lblWelcome = new javax.swing.JLabel("<html><div style='padding:12px'><span style='font-size:20px;font-weight:600;'>Bienvenido Al Restaurante</span><br><span style='font-size:12px;color:#555;'>Administra mesas, platos y pedidos</span></div></html>");
contentPanel.add(lblWelcome, java.awt.BorderLayout.CENTER);


contentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10,10,10,10));


MesasMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uts/edu/fpoo/icons/mesa.png")));
PlatosMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uts/edu/fpoo/icons/plato.png")));

setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        PlatosMenuItem = new javax.swing.JMenuItem();
        MesasMenuItem = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        pedidoEjecucionMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 430));

        jMenu1.setText("Archivos");

        PlatosMenuItem.setText("Platos");
        PlatosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlatosMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(PlatosMenuItem);

        MesasMenuItem.setText("Mesas");
        MesasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesasMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(MesasMenuItem);

        jMenuItem7.setText("Usuarios");
        jMenu1.add(jMenuItem7);

        jMenuItem5.setText("Cambios de clave");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Cambios de usuario");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem8.setText("Cerrar Sesión");
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimientos");

        pedidoEjecucionMenuItem.setText("Pedidos");
        pedidoEjecucionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoEjecucionMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(pedidoEjecucionMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem9.setText("Acerca de");
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Ayuda");
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MesasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesasMenuItemActionPerformed
        MesasVista mv = new MesasVista();
        MesasControlador con = new MesasControlador(mv);
        mv.setVisible(true);
        mv.setLocationRelativeTo(null);

    }//GEN-LAST:event_MesasMenuItemActionPerformed

    private void PlatosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlatosMenuItemActionPerformed
        PlatosVista pv = new PlatosVista();
        PlatosControlador con = new PlatosControlador(pv);
        pv.setVisible(true);
        pv.setLocationRelativeTo(null);
        
        
    }//GEN-LAST:event_PlatosMenuItemActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void pedidoEjecucionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoEjecucionMenuItemActionPerformed

    }//GEN-LAST:event_pedidoEjecucionMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MesasMenuItem;
    private javax.swing.JMenuItem PlatosMenuItem;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem pedidoEjecucionMenuItem;
    // End of variables declaration//GEN-END:variables
}
